<?php

/**
 * @file
 * DrImage core functions.
 */

use \Drupal\Core\Routing\RouteMatchInterface;
use Drupal\drimage\Controller\ImageStyleListBuilder;
use Drupal\drimage\Controller\ImageStyleWithPipelineListBuilder;

/**
 * Implements hook_help().
 */
function drimage_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'drimage.image':
      return '<p>' . t('For a full description of the module, visit the project page: https://drupal.org/project/drimage') . '</p>';
  }
}

/**
 * Implements hook_theme().
 */
function drimage_theme() {
  return [
    'drimage_formatter' => [
      'variables' => [
        'item' => NULL,
        'item_attributes' => NULL,
        'image_style' => NULL,
        'imageapi_optimize_webp' => NULL,
        'url' => NULL,
        'alt' => NULL,
        'width' => NULL,
        'height' => NULL,
        'data' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_entity_type_alter().
 */
function drimage_entity_type_alter(array &$entity_types): void {
  if (isset($entity_types['imageapi_optimize_pipeline'])) {
    $entity_types['image_style']->setListBuilderClass(ImageStyleWithPipelineListBuilder::class);
  } else {
    $entity_types['image_style']->setListBuilderClass(ImageStyleListBuilder::class);
  }
}

/**
 * Implements hook_module_implements_alter().
 *
 * Moves drimage_entity_type_alter to the back, to override the imageapi_optimize override if present.
 */
function drimage_module_implements_alter(array &$implementations, string $hook): void {
  if ($hook == 'entity_type_alter') {
    $group = $implementations['drimage'];
    unset($implementations['drimage']);
    $implementations['drimage'] = $group;
  }
}
