<?php

/**
 * @file
 * Logs comment CUD commands in the event_log_track module.
 */

/**
 * Implements hook_event_log_track_handlers().
 */
function event_log_track_comment_event_log_track_handlers() {
  // Comment event log handler.
  $handlers = [];
  $handlers['comment'] = [
    'title' => t('Comment'),
  ];
  return $handlers;
}

/**
 * Implements hook_comment_insert().
 */
function event_log_track_comment_insert($comment) {
  $log = [
    'type' => 'comment',
    'operation' => 'insert',
    'description' => t('%type: %title', [
      '%type' => $comment->getTypeId(),
      '%title' => $comment->getSubject(),
    ]),
    'ref_numeric' => $comment->id(),
    'ref_char' => $comment->getSubject(),
  ];
  event_log_track_insert($log);
}

/**
 * Implements hook_comment_update().
 */
function event_log_track_comment_update($comment) {
  $log = [
    'type' => 'comment',
    'operation' => 'update',
    'description' => t('%type: %title', [
      '%type' => $comment->getTypeId(),
      '%title' => $comment->getSubject(),
    ]),
    'ref_numeric' => $comment->id(),
    'ref_char' => $comment->getSubject(),
  ];
  event_log_track_insert($log);
}

/**
 * Implements hook_comment_delete().
 */
function event_log_track_comment_delete($comment) {
  $log = [
    'type' => 'comment',
    'operation' => 'delete',
    'description' => t('%type: %title', [
      '%type' => $comment->getTypeId(),
      '%title' => $comment->getSubject(),
    ]),
    'ref_numeric' => $comment->id(),
    'ref_char' => $comment->getSubject(),
  ];
  event_log_track_insert($log);
}
