<?php

/**
 * @file
 * Logs Group entity CUD commands in the event_log_track module.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_event_log_track_handlers().
 */
function event_log_track_group_event_log_track_handlers() {
  $handlers = [];
  // Group event log handler.
  $handlers['group'] = [
    'title' => t('Group'),
  ];

  return $handlers;
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function event_log_track_group_insert(EntityInterface $entity) {
  $log = [
    'type' => 'group',
    'operation' => 'insert',
    'description' => t('%title (%type)%revision_log', [
      '%type' => $entity->bundle(),
      '%title' => $entity->label(),
      '%revision_log' => $entity->getRevisionLogMessage() ? ': ' . $entity->getRevisionLogMessage() : '',
    ]),
    'ref_numeric' => $entity->id(),
    'ref_char' => Html::escape($entity->label()),
  ];

  // Insert log.
  event_log_track_insert($log);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function event_log_track_group_update(EntityInterface $entity) {
  $log = [
    'type' => 'group',
    'operation' => 'update',
    'description' => t('%title (%type)%revision_log', [
      '%type' => $entity->bundle(),
      '%title' => $entity->label(),
      '%revision_log' => $entity->getRevisionLogMessage() ? ': ' . $entity->getRevisionLogMessage() : '',
    ]),
    'ref_numeric' => $entity->id(),
    'ref_char' => Html::escape($entity->label()),
  ];

  // Insert log.
  event_log_track_insert($log);
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function event_log_track_group_delete(EntityInterface $entity) {
  $log = [
    'type' => 'group',
    'operation' => 'delete',
    'description' => t('%title (%type)%revision_log', [
      '%type' => $entity->bundle(),
      '%title' => $entity->label(),
      '%revision_log' => $entity->getRevisionLogMessage() ? ': ' . $entity->getRevisionLogMessage() : '',
    ]),
    'ref_numeric' => $entity->id(),
    'ref_char' => Html::escape($entity->label()),
  ];

  // Insert log.
  event_log_track_insert($log);
}
