<?php

/**
 * @file
 * On-page tool for easier interface translation.
 */

use Drupal\l10n_client_ui\LocalizationClientUi;

/**
 * Returns whether the localization client interface should be added.
 *
 * @return bool
 *   TRUE if the current user can run localization client interface,
 *   and FALSE if not.
 */
function l10n_client_ui_access_tools(): bool {
  return LocalizationClientUi::access();
}

/**
 * Implements hook_toolbar().
 */
function l10n_client_ui_toolbar(): array {
  if (!LocalizationClientUi::access()) {
    return [];
  }

  $tab['l10n_client_ui'] = [
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'html_tag',
      '#tag' => 'button',
      '#value' => t('Translate page'),
      '#attributes' => [
        'class' => ['toolbar-icon', 'toolbar-icon-l10n_client_ui'],
        'role' => 'button',
        'aria-pressed' => 'false',
      ],
    ],
    '#wrapper_attributes' => [
      'class' => ['l10n_client_ui-toolbar-tab'],
      'id' => 'toolbar-tab-l10n_client_ui',
    ],
    '#attached' => [
      'library' => [
        'l10n_client_ui/l10n_client_ui',
      ],
    ],
  ];

  return $tab;
}

/**
 * Implements hook_preprocess_HOOK() for html templates.
 *
 * We use hook_preprocess_html to place our block as late as possible.
 * Despite our block has a lazy_builder, it can be rendered before other
 * lazy built blocks if we place it in hook_preprocess_page.
 *
 * @see \Drupal\l10n_client_ui\Plugin\Block\TranslationBlock
 */
function l10n_client_ui_preprocess_html(&$variables) {
  if (!LocalizationClientUi::access()) {
    return;
  }

  $block_manager = \Drupal::service('plugin.manager.block');
  $config = [];
  $plugin_block = $block_manager->createInstance('l10n_client_ui_translation', $config);
  if ($plugin_block) {
    $access_result = $plugin_block->access(\Drupal::currentUser());
    if ($access_result->isForbidden()) {
      return;
    }
    $render = $plugin_block->build();
    $variables['page_bottom'][] = $render;
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function l10n_client_ui_menu_local_tasks_alter(&$data, $route_name) {
  // This module adds one more settings screen, so modify the existing
  // settings screen to be more specific about what it is doing.
  if (!empty($data['tabs'][0]['locale.settings'])) {
    $data['tabs'][0]['locale.settings']['#link']['title'] = t('Update settings');
  }
}
