<?php

/**
 * @file
 * Track the logs of form submissions or other actions that performed by user.
 */

use Drupal\Core\Installer\InstallerKernel;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function event_log_track_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'help.page.event_log_track') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t("You can track logs of specific events that you'd like to log. The events  by the user (using the forms) are saved in the database and can be viewed on the page admin/reports/events-track. You could use this to track number of times the CUD operation performed by which users. This module required by: Events Log Track User Authentication, Events Log Track Menu, Events Log Track Node, Events Log Track Taxonomy, Events Log Track User.") . '</p>';
    $output .= '<h3>' . t('Uses') . '</h3>';
    $output .= '<dl>';
    $output .= '<dt>' . t('Events Log Track Menu') . '</dt>';
    $output .= '<dd>' . t('Using this submodule you can logs menu CUD events performed by the user. This module requires: Events Log Track.') . '</dd>';
    $output .= '</dl>';
    $output .= '<dl>';
    $output .= '<dt>' . t('Events Log Track Node') . '</dt>';
    $output .= '<dd>' . t('Using this submodule you can logs node CUD events performed by the user. This module requires: Events Log Track.') . '</dd>';
    $output .= '</dl>';
    $output .= '<dl>';
    $output .= '<dt>' . t('Events Log Track Taxonomy') . '</dt>';
    $output .= '<dd>' . t('Using this submodule you can logs taxonomy vocabulary and term CUD events performed by the user. This module requires: Events Log Track.') . '</dd>';
    $output .= '</dl>';
    $output .= '<dl>';
    $output .= '<dt>' . t('Events Log Track User') . '</dt>';
    $output .= '<dd>' . t('Using this submodule you can logs user CUD events performed by the user. This module requires: Events Log Track.') . '</dd>';
    $output .= '</dl>';
    $output .= '<dl>';
    $output .= '<dt>' . t('Events Log Track User Authentication') . '</dt>';
    $output .= '<dd>' . t('Using this submodule you can logs user authentication (login logout and request password). This module requires: Events Log Track.') . '</dd>';
    $output .= '</dl>';

    return $output;
  }
}

/**
 * Inserts the log record in the event log track. Sets the lid.
 *
 * @param array $log
 *   The log record to be saved. This record contains the following fields:
 *   - {string} type
 *     The event type. This is usually the object type that is described by this
 *     event. Example: 'node' or 'user'. Required.
 *   - {string} operation
 *     The operation being performed. Example: 'insert'. Required.
 *   - {string} description
 *     A textual description of the event. Required.
 *   - {string} ref_numeric
 *     Reference to numeric id. Optional.
 *   - {string} ref_char
 *     Reference to alphabetical id. Optional.
 * @param bool $logOnCLI
 *   Should the record also saved on CLI operations.
 */
function event_log_track_insert(array &$log, bool $logOnCLI = FALSE) {
  if (InstallerKernel::installationAttempted()) {
    // Ignore logs during Drupal installation.
    return;
  }

  if (PHP_SAPI === 'cli' && $logOnCLI !== TRUE) {
    // Ignore CLI requests.
    return;
  }

  if (empty($log['created'])) {
    $log['created'] = \Drupal::time()->getRequestTime();
  }

  if (empty($log['uid'])) {
    $account = \Drupal::currentUser();
    $log['uid'] = $account->id();
  }

  $ip = Drupal::request()->getClientIp();
  if (empty($log['ip']) && !empty($ip)) {
    $log['ip'] = $ip;
  }

  if (empty($log['path'])) {
    $log['path'] = Url::fromRoute('<current>')->getInternalPath();
  }

  if (empty($log['ref_numeric'])) {
    $log['ref_numeric'] = NULL;
  }

  if (empty($log['ref_char'])) {
    $log['ref_char'] = NULL;
  }

  // Remove tags from description.
  $log['description'] = strip_tags($log['description']);

  if (\Drupal::moduleHandler()->moduleExists('event_log_track_syslog')) {
    $elog_service = \Drupal::service('logger.eventlog');
    $elog_service->logEvent($log);
  }

  $config = \Drupal::config('event_log_track.adminsettings');
  if (!$config->get('disable_db_logs')) {
    if (empty($log['lid'])) {
      \Drupal::database()->insert('event_log_track')
        ->fields([
          'type' => $log['type'],
          'operation' => $log['operation'],
          'description' => $log['description'],
          'created' => $log['created'],
          'uid' => $log['uid'],
          'ip' => $log['ip'],
          'path' => $log['path'],
          'ref_char' => $log['ref_char'],
          'ref_numeric' => $log['ref_numeric'],
        ])
        ->execute();
    }
    else {
      \Drupal::database()->update('event_log_track')
        ->fields([
          'type' => $log['type'],
          'operation' => $log['operation'],
          'description' => $log['description'],
          'created' => $log['created'],
          'uid' => $log['uid'],
          'ip' => $log['ip'],
          'path' => $log['path'],
          'ref_char' => $log['ref_char'],
          'ref_numeric' => $log['ref_numeric'],
        ])
        ->condition('lid', $log['lid'])
        ->execute();
    }
  }
}

/**
 * Implements hook_cron().
 */
function event_log_track_cron() {
  $config = \Drupal::config('event_log_track.adminsettings');
  if ($config->get('enable_log_deletion')) {
    $event_log_track_service = \Drupal::service('event_log_track.api');
    $old_record = $event_log_track_service->getOldRecords();
    if (!empty($old_record)) {
      $event_log_track_service->deleteOldRecords($old_record);
    }
  }
}

/**
 * Get the number of sessions belonging to a user.
 *
 * @param int $uid
 *   The user ID.
 *
 * @return int
 *   number of sessions.
 */
function _event_log_track_session_count($uid) {
  $count_session = \Drupal::database()->select('sessions', 's')
    ->fields('s', ['sid'])
    ->condition('s.uid', $uid)
    ->countQuery()
    ->execute()
    ->fetchField();

  return (int) $count_session;
}

/**
 * Process the batches.
 */
function _event_log_track_process_old_records($data_chunk, &$context) {
  $db = \Drupal::database();
  $db->delete('event_log_track')
    ->condition('lid', $data_chunk, 'IN')
    ->execute();
}
